from transformers import pipeline
from logger_config import setup_logger

logger = setup_logger()

class FinancialPlannerAI:
    def __init__(self):
        logger.info("Loading AI model...")
        # Load a conversational model suitable for Indonesian language
        # For example, use a multilingual model or a specific Indonesian model if available
        self.nlp = pipeline("conversational", model="microsoft/DialoGPT-medium")
        logger.info("AI model loaded.")

    def generate_response(self, input_text: str) -> str:
        logger.info(f"Generating response for input: {input_text}")
        try:
            response = self.nlp(input_text)
            # Extract generated text from response object
            if response and len(response) > 0:
                generated_text = response[0]['generated_text'] if 'generated_text' in response[0] else str(response[0])
                logger.info(f"Generated response: {generated_text}")
                return generated_text
            else:
                logger.warning("No response generated by AI model.")
                return "Maaf, saya tidak mengerti."
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            return "Terjadi kesalahan saat memproses permintaan Anda."
